import React from 'react'
import ReactDOM from 'react-dom'
import './styles/reset.css'
import 'mapbox-gl/dist/mapbox-gl.css'
import App from './App'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'
// import 'rsuite/lib/styles/index.less'
// import 'semantic-ui-css/semantic.min.css'

ReactDOM.render(<App/>, document.getElementById('root'))